# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

path: /kaggle/input/alprdatasetv3/dataset_merged # change if need

train: images/train
val: images/val

names:
  0: vehicle
  1: license
